[build]
  publish = "dist"

[[redirects]]
  from = "/2022/clean-code-ch3/*"
  to = "/2022/clean-code-ch3/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://sidv.dev"
  status = 302