[build]
  publish = "dist"

## Yarn 3 cache does not work out of the box as of Jan 2022. Context:
## https://github.com/netlify/build/issues/1535#issuecomment-1021947989
[build.environment]
YARN_CACHE_FOLDER = "/opt/buildhome/.yarn_cache"
YARN_VERSION = "3.1.1"

[[redirects]]
  from = "/2022/clean-code-ch3/*"
  to = "/2022/clean-code-ch3/index.html"
  status = 200

[[redirects]]
  from = "/2022/go-basics/*"
  to = "/2022/go-basics/index.html"
  status = 200

[[redirects]]
  from = "/"
  to = "https://sidv.dev"
  status = 302
