[build]
  publish = "dist"

[[redirects]]
  from = "/2022/clean-code-ch3/*"
  to = "/2022/clean-code-ch3/index.html"
  status = 200

[[redirects]]
  from = "/2022/go-basics/*"
  to = "/2022/go-basics/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
