#!/bin/sh
DIRS=$(ls -d */)
echo "$DIRS"
for DIR in $DIRS; do
  DIRNAME=$(echo $DIR | sed 's:/*$::')
  if [ "$DIRNAME" != "dist" ]; then
    cd "$DIRNAME"
    if ! find "$DIRNAME.pdf"; then
      echo "exporting $DIRNAME/$DIRNAME.pdf"
      cd "src"
      yarn export
      cd ../..
    fi
    cd ..
  fi
done
exec git add *.pdf